[workspace]
resolver = "2"

members = [
    "libs/arith_utils",
    "libs/price_provider",
    "pallets/price_feed",
    "pallets/price_feed/rpc",
    "substrate/frame/elections-phragmen",
    "substrate/frame/collective",
    "substrate/frame/staking"
]