[workspace]
resolver = "2"

members = [
    "libs/arith-utils",
    "libs/price-provider",
    "pallets/price-feed",
    "pallets/price-feed/rpc",
    "substrate/frame/elections-phragmen",
    "substrate/frame/collective",
    "substrate/frame/democracy",
    "substrate/frame/staking"
]